# Use a Node.js base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the rest of the application code
COPY . .

# Expose port 3000 for the frontend application
EXPOSE 3000

# Run the development server
CMD ["npm", "start"]
